language: rust
rust: nightly

script:
  - cd additions/rustbook && cargo build --release
  - cp ./target/release/rustbook ./
  - cd ../../ && find . -maxdepth 1 -name '*.md' -exec sed -i 1s/#/%/ {} \;
  - ./additions/rustbook/rustbook build

after_success:
  - test $TRAVIS_BRANCH == "master" && bash additions/deploy.sh

branches:
  only: master

env:
  global:
    - secure: "XQp6IVK0bb5HuMXU8vrtvSCok0CPz5ogneo/3Bkxi+XycjrlqS2Tou/9gmfOl/08cKf5Dw1vNd2SMQIYTREJNe9jZW0pRsnpkcjc3WiGtIKEwlaxWk/RB7uKffhbTzyz1vjnihkqPjDSyyFSYU+EMJdm+ox5SYbUhymeLSSWVB+3a3TkaqZPEZJK+3kphbl8uJG/a4lXcPyLvkzrmVr4gFNywVIXbvgPMxUmF5VHubfaT2E5uEIQnmskQ/QUvNdZs8RW90vagij691a5zBgWLqtZ590GKBBpEYCROgukpGjGTouSDtiJxou4aScqtYA6oVJfll8K/VCkarVwHjEo5Un+X+wc4slNPWxJSK/R8RnfY5JI9gL1D92ViwPnVvagccBP03GbYrqJfpve3g3Vb1Ld8whOn1eLArgl6t8dn6LlDvaD+CemEblpwV4IaTKUqfyNVVRWKoLKUTL0P5TF7UgO71QKZlNHjLS9yo2GR2fXpgIhu57ARbhGOYM81AbyWPjZsZoPq8uffyJx+FzGwJIdVHrybcs4xY4GGY9KoxZxEkuiqdwlTH2GrSnqWwm80z3+j6zu/yIxcrNenkUKLlddpmQhHhSq02mFBgOpunPOWg1VisXciJxiqt8EN4prY6LgQpLBKmPhmpCikZsHnSr1y6rbz6CS/qRQegKd4Lc="
