language: rust
rust: nightly

script:
  - cd additions/rustbook && cargo build --release
  - cp ./target/release/rustbook ./
  - cd ../../ && find . -maxdepth 1 -name '*.md' -exec sed -i 1s/#/%/ {} \;
  - ./additions/rustbook/rustbook build

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash additions/deploy.sh

branches:
  only: master

env:
  global:
    - secure: "niHx/buS5DuXwTngNpi77aIR5185GcnGCicdGoFQk9GEzGvkriYfZwfIGPswJcXIjWHrQpq4MkzOC0GzMUAJMEwKma6HD+dSG7pKDU0+cvjvD4IfPV3bHRmRvdGiD6TTuJ6/G97If8eBl1+gQVFrDBtU5CH1DE1GZGMVDxsw5CxYS29QO2warVnssVpyj/bCJ3S7EgzHdLtfrRani+5r3L28NSlfo7pmPPdesZy7O8uZ2rmMlDd0S+NPPG0UKtrBYqSzBOLy+ar0CNG4HQP6F1FMMpjjDzB6V2Vx4aBTYZalJZb/WZz1GbFHo5Kw5ePsJbS4IbPbsxp8Ps6FaTzTBUWI85vf4FY759zGzo+XQRSKBr7Vgvo9fyPevk7bWM4WixROZq7n8eD8CERKSuS5Te1x6101xG9/XPIgN8XxdWbd0a/Y0Go66722peGlqu0JMTdm+APOFLdmyAt6RjQvvfTXGB/UlPXVOLwib/DZwenyFMnOr3VFj1pH/9rYOiWssA73T2p/GEVUjZunUtSUy0QpcwADqDZbLfmPZTcNa0mI8ChZswyh7qgN+0qSGQqf1xgPOBDukOmfAAcJW7trLyAt6Dr5yYb6XYWbGcIjhsunjgweqtlXaKaKnDHqGocZr0ouaaKbMdhIDRbWuePWAZDdOANzO/yFjydBpPiof0M="
